baqeshahr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    re_path(r'^static/(?P<path>.*)$', serve, {
        'document_root': settings.STATIC_ROOT,
    }),
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),




]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home_menu, name='menu'),
    path("gallery/<int:pk>/", gallery_menu, name='gallery-menu'),


]

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class User(AbstractUser):
    pass

home/models.py
from django.core.exceptions import ValidationError
from django.db import models


# Create your models here.
def min_length(value):
    if len(value) < 5:
        raise ValidationError("عدد حداقلی کم است")


class Category (models.Model):
    name = models.CharField(max_length=15)
    icon = models.ImageField(upload_to= 'category/')

    def __str__(self):
        return self.name


class Item (models.Model):
    name = models.CharField(max_length=15)
    image = models.ImageField(upload_to= 'items/')
    price = models.CharField(max_length=8,validators=[min_length])
    description = models.TextField(max_length=60)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class CategoryForGallery(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class Gallery(models.Model):
    image = models.ImageField(upload_to='gallery/')
    cat = models.ForeignKey(CategoryForGallery, on_delete=models.CASCADE)

account/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render
from .models import *
from django.http import HttpResponse

# Create your views here.


def home_menu(request):
    if request.method == 'GET':
        cate = Category.objects.all()
        cat_all_gallery = CategoryForGallery.objects.all()
        return render(request, 'index.html', context={'cat': cate,
                                                      'all': cat_all_gallery})


def gallery_menu(request, pk):
    if request.method == "GET":
        cat_all_gallery = CategoryForGallery.objects.filter(id=pk)
        cate = Category.objects.all()
        return render(request, 'allgallery.html', context={'all': cat_all_gallery,
                                                           'cat': cate})

templates/allgallery.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>منوی رستوران سنتی</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Nika:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@100..900&display=swap" rel="stylesheet">
</head>

<body>

    <header class="main-header">
        <nav class="navbar navbar-expand-lg fixed-top custom-navbar">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'menu' %}">باغ شهر</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">



                        {% for i in all %}
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'gallery-menu' i.id %}">{{ i.name }}</a>
                        </li>

                        {% endfor %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="hero-section text-center d-flex align-items-center justify-content-center" style="background-image: url('/static/images/54336454.jpg') ">

            <div class="hero-content" >
                <h1>به منوی رستوران ما خوش آمدید</h1>
                <p class="lead">تجربه‌ای بی‌نظیر از طعم‌های اصیل ایرانی</p>
                <a href="{% url 'menu' %}" class="btn btn-primary hero-btn smooth-scroll">مشاهده منو <i
                        class="fas fa-chevron-down ms-2"></i></a>
            </div>
        </div>
    </header>

    <main class="container py-5">

{% for i in all %}

        <section id="{{ i.name }}" class="menu-category py-5">

            <h2 class="section-title text-center mb-5 fade-in-up">{{ i.name }}</h2>
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
            {% for j in i.gallery_set.all %}

                <div class="col menu-item hidden">
                    <div class="card h-100 menu-card">
                        <img src="{{ j.image.url }}"
                            class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">{{ j.cat.name }}</h5>

                            </div>
                        </div>
                    </div>
                </div>
                 {% endfor %}

            </div>

        </section>
{% endfor %}


                <section id="contact" class="contact-section text-center py-5">
            <h2 class="section-title mb-4 fade-in-up">تماس با ما</h2>
            <p class="lead">برای سفارش و اطلاعات بیشتر با ما در تماس باشید:</p>
            <div class="contact-info">
                <p><i class="fas fa-phone-alt"></i> 023-33348441</p>
                <p><i class="fas fa-map-marker-alt"></i>سمنان بلوار 17 شهریور داخل پارک</p>

            </div>
            <div class="social-icons mt-4">
                <a href="#" class="social-icon"><i class="fab fa-instagram"></i></a>
                <a href="#" class="social-icon"><i class="fab fa-telegram-plane"></i></a>
                <a href="#" class="social-icon"><i class="fab fa-whatsapp"></i></a>
            </div>
        </section>

    </main>

    <footer class="main-footer py-4 text-center">
        <p>&copy; 2025 رستوران باغ شهر. تمامی حقوق محفوظ است.</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="../static/script.js"></script>
</body>

</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>منوی رستوران سنتی</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Nika:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@100..900&display=swap" rel="stylesheet">

</head>

<body>

    <header class="main-header">
        <nav class="navbar navbar-expand-lg fixed-top custom-navbar">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'menu' %}">باغ شهر</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        {% for i in cat %}
                        <li class="nav-item">
                            <a class="nav-link smooth-scroll" href="#{{ i.name }}">{{ i.name }}</a>
                        </li>

                        {% endfor %}

                        {% for i in all %}
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'gallery-menu' i.id %}">{{ i.name }}</a>
                        </li>

                        {% endfor %}


                    </ul>
                </div>
            </div>
        </nav>
        <div class="hero-section text-center d-flex align-items-center justify-content-center" style="background-image: url('/static/images/54336454.jpg') ">

            <div class="hero-content" >
                <h1>به منوی رستوران ما خوش آمدید</h1>
                <p class="lead">تجربه‌ای بی‌نظیر از طعم‌های اصیل ایرانی</p>
                <a href="#دسر" class="btn btn-primary hero-btn smooth-scroll">مشاهده منو <i
                        class="fas fa-chevron-down ms-2"></i></a>
            </div>
        </div>
    </header>

    <main class="container py-5">
{% for i in cat %}
        <section id="{{ i.name }}" class="menu-category py-5">

            <h2 class="section-title text-center mb-5 fade-in-up">{{ i.name }}</h2>
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
            {% for j in i.item_set.all %}
                <div class="col menu-item hidden">
                    <div class="card h-100 menu-card">
                        <img src="{{ j.image.url }}"
                            class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">{{ j.name }}</h5>
                            <p class="card-text">{{ j.description }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <span class="item-price">{{ j.price }}</span>
                            </div>
                        </div>
                    </div>
                </div>
                 {% endfor %}

            </div>

        </section>
{% endfor %}


         <section id="contact" class="contact-section text-center py-5">
            <h2 class="section-title mb-4 fade-in-up">تماس با ما</h2>
            <p class="lead">برای سفارش و اطلاعات بیشتر با ما در تماس باشید:</p>
            <div class="contact-info">
                <p><i class="fas fa-phone-alt"></i> 023-33348441</p>
                <p><i class="fas fa-map-marker-alt"></i>سمنان بلوار 17 شهریور داخل پارک.</p>

            </div>
            <div class="social-icons mt-4">
                <a href="#" class="social-icon"><i class="fab fa-instagram"></i></a>
                <a href="#" class="social-icon"><i class="fab fa-telegram-plane"></i></a>
                <a href="#" class="social-icon"><i class="fab fa-whatsapp"></i></a>
            </div>
        </section>

    </main>

    <footer class="main-footer py-4 text-center">
        <p>&copy; 2025 رستوران باغ شهر. تمامی حقوق محفوظ است.</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="../static/script.js"></script>
</body>

</html>